export const DashBoardActionType = {
  SET_SERVER_ERROR_REPONSE: "SET_SERVER_ERROR_RESPONSE",
  GET_USER_SHORTLINK: "GET_USER_SHORTLINK",
  GET_USER_SHORTLINK_SUCCCESS: "GET_USER_SHORTLINK_SUCCESS",
  GET_USER_SHORTLINK_FAILED: "GET_USER_SHORTLINK_FAILED",
  DELETE_USER_SHORTLINK: "DELETE_USER_SHORTLINK",
  DELETE_USER_SHORTLINK_SUCCESS: "DELETE_USER_SHORTLINK_SUCCESS",
  DELETE_USER_SHORTLINK_FAILED: "DELETE_USER_SHORTLINK_FAILED",
  SHOW_LOADER_ON_TARGET_LINK: "SHOW_LOADER_ON_TARGET_LINK",
  REMOVE_LOADER_FROM_TARGET_LINK: "REMOVE_LOADER_FROM_TARGET_LINK",
  REMOVE_TARGET_SHORTLINK_FROM_STATE: "REMOVE_TARGET_SHORTLINK_FROM_STATE",
  ADD_TARGET_SHORTLINK_TO_STATE: "ADD_USER_SHORTLINK_TO_STATE",
};
