import { emailSignInSuccess } from "./user.sction";

export const UserActionType = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  REGISTER_NEW_USER: " REGISTER_NEW_USER",
  REGISTRATION_SUCCEEDED: "REGISTRATION_SUCCEEDED ",
  REGISTRATION_FAILED: "REGISTRATION_FAILED",
  REGISTRATION_DONE: "REGISTRATION_DONE",
  GOOGLE_SIGN_IN_START: "GOOGLE_SIGN_IN_START",
  GOOGLE_SIGN_IN_SUCCESS: " GOOGLE_SIGN_IN_SUCCESS",
  GOOGLE_SIGN_IN_FAILED: " GOOGLE_SIGN_IN_FAILED",
  GOOGLE_SIGN_IN_DONE: "GOOGLE_SIGN_IN_DONE",
  EMAIL_SIGN_IN_START: "EMAIL_SIGN_IN_START",
  EMAIL_SIGN_IN_SUCCESS: "EMAIL_SIGN_IN_SUCCESS",
  EMAIL_SIGN_IN_FAILED: "EMAIL_SIGN_IN_FAILED",
  CHECK_USER_SESSION: "CHECK_USER_SESSION",
  SIGN_OUT_USER: "SIGN_OUT_USER",
  SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
  SIGN_OUT_FAILED: "SIGN_OUT_FAILED",
  ADD_NEW_SHORT_LINK: "ADD_NEW_SHORT_LINK",
  INVALID_LINK: "INVALID_LINK",
  SET_USER_ID_TOKEN: " SET_USER_ID_TOKEN",
  TOGGLE_PROFILE_LOADING_STATE: "TOGGLE_PROFILE_LOADING_STATE",
};
